name: Trigger Assets (Testnet)

on:
  workflow_call: # is called from publish-release workflow
  workflow_dispatch: # manual trigger

jobs:
  trigger-assets-testnet:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger xion-assets testnet workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: burnt-labs/xion-assets
          event-type: xion-assets-testnet-release-trigger # NOTICE: must match the trigger in xion-assets workflow
          client-payload: |
            {
              "tag_name": "${{ github.event.release.tag_name }}",
              "release_name": "${{ github.event.release.name }}"
            }

